### PR TITLE
Port PyHeufyBot's Tell command

### PR DESCRIPTION
**Pull request by Heufneutje**

### CODE REVIEW

**Review by HubbeKing — CHANGES_REQUESTED** [review]
No helptext for any of the 4 commands

**Comment by Heufneutje** [comment]
Fixed.

**Review by HubbeKing — APPROVED** [review]
look good to me, nothing jumps out at me as being borked anyway.

**Review by StarlitGhost — APPROVED** [review]
Looks good to me, let's do the merge thing

**Pull request merged**
