### PR TITLE
Port PyHeufyBot's UserLocation, GeoLocation and OpenWeatherMap

### PR DESCRIPTION
**Pull request by Heufneutje**
- UserLocation
- GeoLocation
- OpenWeatherMap

We might wanna just do a separate PR for each module. Seems like less of a hassle that way. I've moved the checklist to https://github.com/DesertBot/DesertBot/issues/138. So this is ready for merging now.

### CODE REVIEW

**Comment by StarlitGhost** [comment]
Obfuscating tells in the database would be nice, could be as simple as base64 encoding.
We can't fully encrypt stuff because there are no user accounts or passwords (and I don't think we want there to be), but I'd rather not read people's PM tells if I'm looking at that table for some reason. And if we're encoding PM tells we might as well do them all.

**Review by HubbeKing — COMMENTED** [review]
Looks good to me? Might wanna add some testcommands to travis to see if the unicode weather symbols cause it to pitch a fit or not, though.

**Comment by Heufneutje** [comment]
Sounds good. Let's see what Travis does.

**Review by StarlitGhost — APPROVED** [review]
Looks good to me

**Pull request merged**
