### PR TITLE
[Tell] Add pmtell and pmtellafter commands

### PR DESCRIPTION
**Pull request by HubbeKing**
This way one can send PM tells from the channel in case one doesn't want tells to a certain user to spam the channel.

Tells sent as PMs to the bot are always PM tells, as they already were.

I don't really know how necessary this is, but I felt like making it. Comfort coding!

### CODE REVIEW

**Review by Heufneutje — APPROVED** [review]
~LGTM~

**Review by Heufneutje — CHANGES_REQUESTED** [review]
Actually scratch that. It seems Travis ran into an error related to this PR.

**Comment by HubbeKing** [comment]
hmm. build succeeds, but it looks like I broke Tells. I'll look at this more after work.

**Review by Heufneutje — APPROVED** [review]
Should be good to merge now.

**Pull request merged**
