### PR TITLE
Apikeys action rework

### PR DESCRIPTION
**Pull request by HubbeKing**
Since the new APIKeys module has an action for fetching API keys, I thought I might as well use it and get rid of the old `utils.api_keys` file.

This probably needs a bit of manual testing, to make sure everything still works? 
I'm not sure I did actions right...

### CODE REVIEW

**Review by StarlitGhost — APPROVED** [review]
Travis says the weather API key still works, and all the rest are loaded the same way so I assume they're fine

**Comment by HubbeKing** [comment]
Should we maybe move it from `commands` to `util` ? It's kinda both. It's a command module, but it is a utility for other modules to use... (see #14 ?)

**Comment by Heufneutje** [comment]
I think moving it to util would be a good idea.

**Review by Heufneutje — COMMENTED** [review]
Looks good to me. I feel like `apikeys-getkey` is a bit of a long action name though mainly cause it has the word key twice. `get-api-key` would work just as well in my opinion.

**Review by Heufneutje — COMMENTED** [review]
Or `get-apikey` for that matter (GitHub won't let me edit my review comment).

**Comment by HubbeKing** [comment]
Alright, I'll move it to the util module folder and rename the action when I get home. 
Also need to add exception handling for if the APIkeys file doesn't exist.

**Comment by HubbeKing** [comment]
Okay, I've somehow managed to break it while renaming the action. Sigh.

Except it works fine during manual testing? What.

**Pull request merged**
