### PR TITLE
Add docker-based github action for tests

### PR DESCRIPTION
**Pull request by HubbeKing**
Needs some secrets for API key decryption and some tweaking probably.

If we add dockerhub credentials it can even handle that part, since we're already building as part of testing.

### CODE REVIEW

**Comment by HubbeKing** [comment]
once this works we can also delete the travis testing config and just use only this

**Comment by HubbeKing** [comment]
Okay. Build works now, but it needs the API keys for all the tests to work right, and credentials to docker hub for the push part to work.

And we need to make it only push starlitghost/desertbot:latest if it's on master and not a PR

**Comment by HubbeKing** [comment]
This should be good to merge now. We should probably disable the automated builds on docker hub first, though, since a push to master will now run a build-test-push cycle on Github

**Comment by StarlitGhost** [comment]
I've disabled dockerhub auto-builds and travis, we should be good to merge now?

**Comment by HubbeKing** [comment]
Should be good to merge, yeah. Then we'll see if the login & push parts work =P

**Pull request merged**
