### PR TITLE
[LogSearch] Add commands for returning all results

### PR DESCRIPTION
**Pull request by HubbeKing**
I also prettified the other function calls in LogSearch, so it's a bit clearer what's going on.

### CODE REVIEW

**Comment by HubbeKing** [comment]
IDK if this is a necessarily a good idea though? 
Since this makes it trivial to retrieve everything someone has ever said, or every mention of something, which has some abuse potential...

**Comment by HubbeKing** [comment]
Would appreciate your thoughts before I just blindly merge this

**Review by Heufneutje — APPROVED** [review]
LGTM

**Review by StarlitGhost — APPROVED** [review]
I don't think anyone in our community in particular would abuse this, and it would be easy enough to restrict it to bot admins and channel mods if we need to.

**Comment by HubbeKing** [comment]
Hm. looks like an unrelated error in MediaWiki - looks like a timeout or failure fetching from a wiki. Merging this, gonna look at MediaWiki later.

**Pull request merged**
