### PR TITLE
Use datastore system in APIKeys module

### PR DESCRIPTION
**Pull request by HubbeKing**

### CODE REVIEW

**Review by Heufneutje — APPROVED** [review]
Looks good to me. We do lose the ability to use it for multiple servers but I feel like that's not that big a deal.

**Comment by HubbeKing** [comment]
Travis isn't loading the APIKeys properly yet, so I think data/localhost/APIKeys.json isn't the right path...

**Comment by HubbeKing** [comment]
Should be ready for merge now, if we do wanna make API keys server-specific. If we don't, I think the existing system works okay.
Might be worth thinking about how to do global storage stuff with DataStore, currently that's all handled by data/defaults, but I don't wanna have API keys in the repo, even if we could encrypt them...

**Review by StarlitGhost — APPROVED** [review]
Looks good to me, we can just use the same keys for multiple servers anyway. I think the duplication is fine in this case.

**Pull request merged**
